name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Day-2-basic-code-tfvars

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6   # or the version you need

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
