name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1   # change to your region

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0   # adjust to your version

      # Terraform Init
      - name: Terraform Init
        working-directory: Day-2-basic-code-tfvars
        run: terraform init

      # Terraform Plan
      - name: Terraform Plan
        working-directory: Day-2-basic-code-tfvars
        run: terraform plan
